import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import starlight from "@astrojs/starlight";
import { rehypeScrollableTables } from "./scripts/rehype-scrollable-tables.mjs";
// Dependency-free by design so importing it here cannot pull generated JSON into the
// config's load graph — see the header of src/data/social-card.ts.
import {
  SITE_URL,
  SOCIAL_IMAGE_ALT,
  SOCIAL_IMAGE_HEIGHT,
  SOCIAL_IMAGE_PATH,
  SOCIAL_IMAGE_WIDTH
} from "./src/data/social-card";

// Starlight owns ONLY /docs. The marketing routes (/, /product, /apps, /security,
// /release) keep their own layout and design tokens — Starlight's `prerender` scope is
// its content collection, so the two coexist without competing for a layout.
//
// Everything under src/content/docs/ is GENERATED by scripts/sync-docs.mjs from the
// pinned core commit and is gitignored. Never commit a copy of a core doc here: one
// canonical source is the whole point, and a committed copy is a copy that drifts.
export default defineConfig({
  site: SITE_URL,
  output: "static",
  // ONE URL per page. Astro emits `/product/index.html` and writes `/product` into every
  // canonical, og:url and sitemap entry; `vercel.json`'s `"trailingSlash": false` is the
  // other half of this and 308-redirects `/product/` onto it. Both halves are required:
  // with Vercel's default (the key absent) BOTH forms answered 200 on production, which
  // is duplicate content that only rel=canonical was holding together.
  trailingSlash: "never",
  // Starlight's integration sets `scopedStyleStrategy: 'where'` GLOBALLY
  // (@astrojs/starlight/index.ts, in its astro:config:setup updateConfig call).
  // That rewrites every component's scoped selectors from `[data-astro-cid-x]` to
  // `:where(.astro-x)` — zero specificity — which silently reflowed the MARKETING
  // pages: the home page lost 56px of height and three visual baselines failed with
  // no source change. Pinning the strategy here keeps the pre-Starlight cascade for
  // the whole site; /docs styling is unaffected because Starlight's own CSS does not
  // rely on it. Do not remove without re-running the visual suite.
  scopedStyleStrategy: "attribute",
  integrations: [
    react(),
    starlight({
      title: "PersonalClaw docs",
      // No `tagline` here: Starlight 0.42.0 removed the option outright (withastro/starlight#3572,
      // "Removes the `tagline` configuration option, which was never used" — no replacement). It
      // had rendered nowhere on 0.41 either, so dropping it changes no pixel; the sentence it
      // carried ("generated from the tagged source this site was built from") was never shown to
      // a reader. If that fact is worth surfacing, it belongs in page content, not in a key the
      // framework ignored.
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/PersonalClaw/PersonalClaw"
        }
      ],
      // Starlight >=0.39 requires an autogenerated group to wrap its config in
      // `items` rather than sitting beside a `label`.
      sidebar: [
        { label: "Guides", items: [{ autogenerate: { directory: "docs/guides" } }] },
        { label: "Reference", items: [{ autogenerate: { directory: "docs/reference" } }] },
        { label: "Architecture", items: [{ autogenerate: { directory: "docs/architecture" } }] },
        { label: "Security", items: [{ autogenerate: { directory: "docs/security" } }] },
        // Last in the sidebar on purpose: the research corpus is background on how the
        // product was designed, not instructions for using it, and its own index page
        // says so before a reader gets to a topic.
        { label: "Research", items: [{ autogenerate: { directory: "docs/research" } }] }
      ],
      // Starlight does not use BaseLayout.astro, so every head tag BaseLayout emits has
      // to be restated for /docs — which is three quarters of the indexable site.
      //
      // How this merges: Starlight's `createHead(defaults, config.head, frontmatter.head)`
      // dedupes `<meta>` by `name`/`property` and the LATER source wins
      // (@astrojs/starlight/utils/head.js `mergeHead`). So entries here both ADD tags
      // Starlight has no default for and OVERRIDE the defaults it does — no duplicate
      // tag is emitted either way. Per-PAGE metadata (the JSON-LD graph) cannot come
      // from this static array; it comes from the `Head` override below.
      // The robots policy is NOT here: it needs per-page knowledge (Starlight's generated
      // 404 must be noindex while every real doc is indexable), so it is emitted by the
      // `Head` override below. Stating it in both places would put two conflicting
      // `<meta name="robots">` tags on one page.
      head: [
        // The social card. Measured on origin/main: docs pages carried NO og:image at
        // all, so every shared /docs link rendered as a bare text row in Slack, X and
        // LinkedIn. Same file, dimensions and alt text as the marketing routes
        // (src/data/structured-data.ts) — the numbers are the PNG's real size.
        {
          tag: "meta",
          attrs: {
            property: "og:image",
            content: `${SITE_URL}${SOCIAL_IMAGE_PATH}`
          }
        },
        { tag: "meta", attrs: { property: "og:image:width", content: SOCIAL_IMAGE_WIDTH } },
        { tag: "meta", attrs: { property: "og:image:height", content: SOCIAL_IMAGE_HEIGHT } },
        { tag: "meta", attrs: { property: "og:image:alt", content: SOCIAL_IMAGE_ALT } },
        {
          tag: "meta",
          attrs: {
            name: "twitter:image",
            content: `${SITE_URL}${SOCIAL_IMAGE_PATH}`
          }
        },
        { tag: "meta", attrs: { name: "twitter:image:alt", content: SOCIAL_IMAGE_ALT } },
        // OVERRIDES of Starlight's own defaults, both of which made /docs look like a
        // separate property:
        //   · og:site_name defaults to Starlight's `title` ("PersonalClaw docs"), so a
        //     docs card and a marketing card advertised two different sites. The same
        //     reasoning already governs the favicon a few lines down.
        //   · og:locale defaults to the bare lang tag ("en"); the Open Graph spec wants
        //     `language_TERRITORY`, which is what the marketing routes emit.
        { tag: "meta", attrs: { property: "og:site_name", content: "PersonalClaw" } },
        { tag: "meta", attrs: { property: "og:locale", content: "en_US" } }
      ],
      // The marketing site is the home; don't strand a reader inside /docs.
      components: {
        // Adds the per-page JSON-LD graph, built by the SAME module BaseLayout uses so
        // the two renderers cannot publish two different shapes. See the file's header.
        Head: "./src/components/DocsHead.astro"
      },
      editLink: {
        // Docs are owned by core, so "edit this page" must point AT core — pointing
        // at this repo would invite a PR that the drift check then deletes.
        baseUrl: "https://github.com/PersonalClaw/PersonalClaw/edit/main/"
      },
      // Zero telemetry is a product feature and extends to this site: Starlight's
      // default search (Pagefind) is fully local, no external service.
      pagefind: true,
      // Same mark the marketing pages use (BaseLayout.astro), so /docs doesn't
      // announce itself as a different property.
      favicon: "/brand/personalclaw-mark.svg",
      // Colour only — see the note in docs.css. Starlight's own layout/type/contrast
      // work is left intact rather than re-derived.
      customCss: ["./src/styles/docs.css"]
    }),
    sitemap(),
    // Runs AFTER starlight, so its updateConfig wins the last write. Starlight sets
    // `scopedStyleStrategy: 'where'` globally; that is right for its own pages but it
    // silently reflowed the marketing pages (see the note above).
    {
      name: "personalclaw:preserve-scoped-style-strategy",
      hooks: {
        "astro:config:setup": ({ updateConfig }) => {
          updateConfig({ scopedStyleStrategy: "attribute" });
        }
      }
    }
  ],
  markdown: {
    // Core's docs are table-heavy and a wide table scrolls; without this the region is
    // mouse-scrollable but keyboard-unreachable (axe: scrollable-region-focusable,
    // serious). See scripts/rehype-scrollable-tables.mjs.
    //
    // Astro 7 prints a deprecation notice for `rehypePlugins` (Sätteri is now the
    // default Markdown processor) and points at `unified()` from
    // @astrojs/markdown-remark. That migration is NOT taken here: the exported
    // `unified` has no `.use()` — `unified().use(...)` throws at config load — so the
    // documented replacement does not work against 7.1.4 as installed. Keeping the
    // supported-and-working form and revisiting when the new API is usable; the notice
    // is a warning, not a failure.
    rehypePlugins: [rehypeScrollableTables]
  },
  image: {
    responsiveStyles: true
  }
});
