import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import starlight from "@astrojs/starlight";
import { rehypeScrollableTables } from "./scripts/rehype-scrollable-tables.mjs";

// Starlight owns ONLY /docs. The marketing routes (/, /product, /apps, /security,
// /release) keep their own layout and design tokens — Starlight's `prerender` scope is
// its content collection, so the two coexist without competing for a layout.
//
// Everything under src/content/docs/ is GENERATED by scripts/sync-docs.mjs from the
// pinned core commit and is gitignored. Never commit a copy of a core doc here: one
// canonical source is the whole point, and a committed copy is a copy that drifts.
export default defineConfig({
  site: "https://personalclaw.dev",
  output: "static",
  trailingSlash: "never",
  // Starlight's integration sets `scopedStyleStrategy: 'where'` GLOBALLY
  // (@astrojs/starlight/index.ts, in its astro:config:setup updateConfig call).
  // That rewrites every component's scoped selectors from `[data-astro-cid-x]` to
  // `:where(.astro-x)` — zero specificity — which silently reflowed the MARKETING
  // pages: the home page lost 56px of height and three visual baselines failed with
  // no source change. Pinning the strategy here keeps the pre-Starlight cascade for
  // the whole site; /docs styling is unaffected because Starlight's own CSS does not
  // rely on it. Do not remove without re-running the visual suite.
  scopedStyleStrategy: "attribute",
  integrations: [
    react(),
    starlight({
      title: "PersonalClaw docs",
      // The docs describe a released version exactly; say which one, since the
      // corpus is generated from that tag rather than written alongside it.
      tagline: "Generated from the tagged source this site was built from.",
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/PersonalClaw/PersonalClaw"
        }
      ],
      // Starlight >=0.39 requires an autogenerated group to wrap its config in
      // `items` rather than sitting beside a `label`.
      sidebar: [
        { label: "Guides", items: [{ autogenerate: { directory: "docs/guides" } }] },
        { label: "Reference", items: [{ autogenerate: { directory: "docs/reference" } }] },
        { label: "Architecture", items: [{ autogenerate: { directory: "docs/architecture" } }] },
        { label: "Security", items: [{ autogenerate: { directory: "docs/security" } }] }
      ],
      // Starlight does not use BaseLayout.astro, so it needs the same robots policy
      // stated here: a Vercel PREVIEW deployment must never be indexable, or a
      // throwaway branch URL competes with personalclaw.dev in search results.
      // (validate:preview enforces this — it caught the omission.)
      head: [
        {
          tag: "meta",
          attrs: {
            name: "robots",
            content:
              process.env.VERCEL_ENV === "preview"
                ? "noindex, nofollow"
                : "index, follow"
          }
        }
      ],
      // The marketing site is the home; don't strand a reader inside /docs.
      components: {},
      editLink: {
        // Docs are owned by core, so "edit this page" must point AT core — pointing
        // at this repo would invite a PR that the drift check then deletes.
        baseUrl: "https://github.com/PersonalClaw/PersonalClaw/edit/main/"
      },
      // Zero telemetry is a product feature and extends to this site: Starlight's
      // default search (Pagefind) is fully local, no external service.
      pagefind: true,
      // Same mark the marketing pages use (BaseLayout.astro), so /docs doesn't
      // announce itself as a different property.
      favicon: "/brand/personalclaw-mark.svg",
      // Colour only — see the note in docs.css. Starlight's own layout/type/contrast
      // work is left intact rather than re-derived.
      customCss: ["./src/styles/docs.css"]
    }),
    sitemap(),
    // Runs AFTER starlight, so its updateConfig wins the last write. Starlight sets
    // `scopedStyleStrategy: 'where'` globally; that is right for its own pages but it
    // silently reflowed the marketing pages (see the note above).
    {
      name: "personalclaw:preserve-scoped-style-strategy",
      hooks: {
        "astro:config:setup": ({ updateConfig }) => {
          updateConfig({ scopedStyleStrategy: "attribute" });
        }
      }
    }
  ],
  markdown: {
    // Core's docs are table-heavy and a wide table scrolls; without this the region is
    // mouse-scrollable but keyboard-unreachable (axe: scrollable-region-focusable,
    // serious). See scripts/rehype-scrollable-tables.mjs.
    //
    // Astro 7 prints a deprecation notice for `rehypePlugins` (Sätteri is now the
    // default Markdown processor) and points at `unified()` from
    // @astrojs/markdown-remark. That migration is NOT taken here: the exported
    // `unified` has no `.use()` — `unified().use(...)` throws at config load — so the
    // documented replacement does not work against 7.1.4 as installed. Keeping the
    // supported-and-working form and revisiting when the new API is usable; the notice
    // is a warning, not a failure.
    rehypePlugins: [rehypeScrollableTables]
  },
  image: {
    responsiveStyles: true
  }
});
