import { access, readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { load } from "cheerio";
import {
  canonicalUrl,
  descriptionExemptOutputPaths,
  outputPathRoute,
  routeOutputPath,
  allRoutePaths,
  blogRoutes,
  compareRoutes,
  crossLinkedDocsRoutes,
  DOCS_BODY_TEXT_FLOOR,
  docsRoutes,
  HEAD_CONTRACT_PAGE_FLOOR,
  llmsFullPath,
  llmsIndexPath,
  LLMS_FULL_BYTE_FLOOR,
  LLMS_INDEX_BYTE_FLOOR,
  qualityRoutes,
  registryAppRoutePaths,
  DOCS_CROSS_LINK_FLOOR,
  routes,
  siteOrigin,
  socialImagePath
} from "../tests/support/site-contract.mjs";
import { registryArtifactExists, registryListing } from "../src/data/registry.mjs";

const root = process.cwd();
const distDir = path.resolve(root, process.env.DIST_DIR ?? "dist");
const expectNoIndex = process.env.EXPECT_NOINDEX === "1";
const failures = [];
const releaseFacts = JSON.parse(
  await readFile(path.join(root, ".generated", "release-facts.json"), "utf8")
);

const fail = (message) => failures.push(message);

async function exists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function localOutputPath(urlPath) {
  const decoded = decodeURIComponent(urlPath);
  if (decoded === "/") return path.join(distDir, "index.html");
  if (path.extname(decoded)) return path.join(distDir, decoded.slice(1));
  return path.join(distDir, decoded.slice(1), "index.html");
}

async function readHtml(routePath) {
  const filePath = path.join(distDir, routeOutputPath(routePath));
  return load(await readFile(filePath, "utf8"));
}

async function collectFiles(directory, predicate, collected = []) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      await collectFiles(entryPath, predicate, collected);
    } else if (predicate(entry.name)) {
      collected.push(entryPath);
    }
  }
  return collected;
}

function metaContent($, selector) {
  return $(selector).attr("content")?.trim() ?? "";
}

async function validateInternalUrl(rawUrl, currentRoute, context, checkHash = false) {
  if (
    rawUrl.startsWith("data:") ||
    rawUrl.startsWith("mailto:") ||
    rawUrl.startsWith("tel:")
  ) {
    return;
  }

  let parsed;
  try {
    parsed = new URL(rawUrl, new URL(currentRoute, siteOrigin));
  } catch {
    fail(`${currentRoute}: invalid ${context} URL "${rawUrl}"`);
    return;
  }

  if (!["http:", "https:"].includes(parsed.protocol)) {
    fail(`${currentRoute}: unsupported ${context} protocol in "${rawUrl}"`);
    return;
  }

  if (parsed.origin !== siteOrigin) {
    if (parsed.protocol !== "https:") {
      fail(`${currentRoute}: external ${context} URL must use HTTPS: "${rawUrl}"`);
    }
    return;
  }

  const outputPath = localOutputPath(parsed.pathname);
  if (!(await exists(outputPath))) {
    fail(`${currentRoute}: broken internal ${context} URL "${rawUrl}"`);
    return;
  }

  if (checkHash && parsed.hash) {
    const targetRoute = parsed.pathname || currentRoute;
    const target$ = await readHtml(targetRoute);
    const id = decodeURIComponent(parsed.hash.slice(1));
    const found = target$("[id]").toArray().some((element) => target$(element).attr("id") === id);
    if (!found) {
      fail(`${currentRoute}: missing fragment target "${rawUrl}"`);
    }
  }
}

// Resolved once, before any sweep: the published docs route set is generated by
// `npm run sync` (src/data/docs-index.mjs), and reading it here means a missing artifact
// fails with that module's explicit "run npm run sync" message rather than partway
// through a sweep.
const docsRoutePaths = docsRoutes();
const crossLinkedRoutePaths = crossLinkedDocsRoutes();

const generatedHtml = new Set(
  (await collectFiles(distDir, (fileName) => fileName.endsWith(".html"))).map((filePath) =>
    path.relative(distDir, filePath)
  )
);
// The registry artifact must EXIST by the time a build is validated. Without this the
// listing surface degrades into a clean-looking empty page and every check below it
// passes while measuring nothing — the failure mode this whole tier is written against.
if (!registryArtifactExists()) {
  fail(
    ".generated/registry.json is missing: the registry pages rendered without their " +
      "source, which is indistinguishable from an empty registry. Run `npm run sync`."
  );
}

const registryAppPaths = registryArtifactExists() ? await registryAppRoutePaths() : [];
const contractedHtml = new Set(
  [...allRoutePaths(), ...registryAppPaths].map((routePath) => routeOutputPath(routePath))
);
// Starlight emits its own 404 page; it is a real published artifact, not drift.
contractedHtml.add("404.html");
for (const filePath of generatedHtml) {
  if (!contractedHtml.has(filePath)) fail(`generated route ${filePath} is missing from the route contract`);
}
for (const filePath of contractedHtml) {
  if (!generatedHtml.has(filePath)) fail(`route contract references missing generated page ${filePath}`);
}

// ── The universal head contract ──────────────────────────────────────────────────
//
// Derived from the BUILD OUTPUT, not from a list of routes. That is the whole point: a
// new page — a docs topic, a registry listing, a route another branch adds — is held to
// this the moment it renders, with no edit here and no edit to the route contract's
// per-tier tables. What each TIER additionally contracts (exact title strings, a docs
// body floor, a registry render) stays in its own block below; this block owns the head
// fields that every indexable page needs regardless of who wrote its words.
//
// It exists because the per-tier tables left most of the site uncovered, and the gap was
// invisible: on origin/main all 33 generated /docs pages shipped with NO `og:image` (so
// every shared docs link rendered as a bare text row) and NO JSON-LD at all, and the
// per-listing registry pages were swept by a loop over a list that is EMPTY until the
// pin moves — a metadata contract that passes because it measures nothing.
const socialImageUrl = `${siteOrigin}${socialImagePath}`;
// Measured from the artifact rather than compared against a second copy of the numbers:
// a PNG's IHDR is bytes 16..24 of the file. A card whose declared dimensions do not match
// its pixels is cropped by the consumer, and nothing else in the build would notice.
const socialImageHeader = await readFile(path.join(distDir, socialImagePath.slice(1)));
const socialImageWidth = String(socialImageHeader.readUInt32BE(16));
const socialImageHeight = String(socialImageHeader.readUInt32BE(20));

/** Absolute in-site URLs a BreadcrumbList claims; resolved after the sweep. */
const breadcrumbItemUrls = new Map();
let headContractPages = 0;

for (const outputPath of [...generatedHtml].sort()) {
  const routePath = outputPathRoute(outputPath);
  const $ = load(await readFile(path.join(distDir, outputPath), "utf8"));
  const canonical = canonicalUrl(routePath);
  headContractPages += 1;

  const title = $("title").text().trim();
  const description = metaContent($, 'meta[name="description"]');
  const requiresDescription = !descriptionExemptOutputPaths.has(outputPath);

  if ($("html").attr("lang") !== "en") fail(`${routePath}: html lang must be "en"`);
  if (!title) fail(`${routePath}: page has no title`);
  else if (!title.includes("PersonalClaw")) {
    fail(`${routePath}: title "${title}" is missing the site name`);
  }
  if (requiresDescription && !description) {
    fail(`${routePath}: page has no meta description`);
  }
  if ($("h1").length !== 1) {
    fail(`${routePath}: expected exactly one h1, found ${$("h1").length}`);
  }
  if ($('link[rel="canonical"]').attr("href") !== canonical) {
    fail(
      `${routePath}: canonical must be ${canonical} ` +
        `(got ${$('link[rel="canonical"]').attr("href") ?? "none"})`
    );
  }

  // ONE robots tag, and the right one. Exactly one, because the policy is stated in two
  // renderers (BaseLayout and the Starlight head override) and Google resolves
  // conflicting tags to the most restrictive — a second tag would silently deindex a
  // page. `/404` is `noindex` on both renderers' terms: nothing there ranks.
  const robotsTags = $('meta[name="robots"]');
  const expectedRobots = expectNoIndex
    ? "noindex, nofollow"
    : routePath === "/404"
      ? "noindex, follow"
      : "index, follow";
  if (robotsTags.length !== 1) {
    fail(`${routePath}: expected exactly one robots meta tag, found ${robotsTags.length}`);
  } else if (robotsTags.attr("content")?.trim() !== expectedRobots) {
    fail(
      `${routePath}: robots meta must be "${expectedRobots}" ` +
        `(got "${robotsTags.attr("content")}")`
    );
  }

  // The share card. Every tag here is required on every page: a page with og:title but
  // no og:image renders in Slack, X and LinkedIn as a bare text row, which is the exact
  // state /docs shipped in.
  const socialContract = [
    ['meta[property="og:site_name"]', "PersonalClaw"],
    ['meta[property="og:locale"]', "en_US"],
    ['meta[property="og:url"]', canonical],
    ['meta[property="og:image"]', socialImageUrl],
    ['meta[property="og:image:width"]', socialImageWidth],
    ['meta[property="og:image:height"]', socialImageHeight],
    ['meta[name="twitter:card"]', "summary_large_image"],
    ['meta[name="twitter:image"]', socialImageUrl]
  ];
  if (requiresDescription) {
    socialContract.push(
      ['meta[property="og:description"]', description],
      ['meta[name="twitter:description"]', description]
    );
  }
  for (const [selector, expected] of socialContract) {
    if (metaContent($, selector) !== expected) {
      fail(
        `${routePath}: ${selector} must equal "${expected}" ` +
          `(got "${metaContent($, selector)}")`
      );
    }
  }
  // The card headline must be non-empty and must be describing THIS page. Prefix, not
  // equality, because the two tiers differ for a reason: the marketing routes carry the
  // suffixed `<title>` verbatim, while /docs carries the bare heading, since a card
  // renders `og:site_name` beside the title and would otherwise print the site's name
  // twice. A prefix check accepts both and still fails a headline from another page.
  for (const selector of ['meta[property="og:title"]', 'meta[name="twitter:title"]']) {
    const value = metaContent($, selector);
    if (!value) fail(`${routePath}: ${selector} must be non-empty`);
    else if (!title.startsWith(value)) {
      fail(`${routePath}: ${selector} "${value}" does not match the <title> "${title}"`);
    }
  }
  // Alt text on the card, non-empty: a share preview is an image a screen reader has to
  // describe, and the a11y gate cannot see a meta tag.
  for (const selector of [
    'meta[property="og:image:alt"]',
    'meta[name="twitter:image:alt"]'
  ]) {
    if (!metaContent($, selector)) fail(`${routePath}: ${selector} must be non-empty`);
  }
  if (!metaContent($, 'meta[property="og:type"]')) {
    fail(`${routePath}: og:type must be set`);
  }

  // Structured data. One document, valid, and anchored to this page: an invalid graph is
  // worse than no graph, because a consumer that fails to parse it discards every claim
  // in it rather than the one that is wrong.
  const jsonLdScripts = $('script[type="application/ld+json"]');
  if (jsonLdScripts.length !== 1) {
    fail(
      `${routePath}: expected exactly one JSON-LD document, found ${jsonLdScripts.length}`
    );
  } else {
    try {
      const jsonLd = JSON.parse(jsonLdScripts.text());
      const graph = Array.isArray(jsonLd["@graph"]) ? jsonLd["@graph"] : [];
      if (jsonLd["@context"] !== "https://schema.org" || graph.length === 0) {
        fail(`${routePath}: JSON-LD must be a non-empty schema.org @graph`);
      }
      const ofType = (type) => graph.filter((node) => node["@type"] === type);

      const [webPage] = ofType("WebPage");
      if (!webPage) fail(`${routePath}: JSON-LD graph must carry a WebPage node`);
      else {
        if (webPage.url !== canonical) fail(`${routePath}: JSON-LD URL must match canonical`);
        if (webPage.name !== title) {
          fail(`${routePath}: JSON-LD WebPage name must equal the <title>`);
        }
        if (requiresDescription && webPage.description !== description) {
          fail(`${routePath}: JSON-LD WebPage description must equal the meta description`);
        }
      }

      const [webSite] = ofType("WebSite");
      if (webSite?.url !== `${siteOrigin}/`) {
        fail(`${routePath}: JSON-LD website URL must be ${siteOrigin}/`);
      }
      if (ofType("Organization").length !== 1) {
        fail(`${routePath}: JSON-LD graph must carry exactly one Organization node`);
      }
      // The product identity node is scoped to the home page: exactly one there, none
      // anywhere else — a second SoftwareApplication would compete with it.
      const appNodes = ofType("SoftwareApplication").length;
      if (routePath === "/" ? appNodes !== 1 : appNodes !== 0) {
        fail(`${routePath}: SoftwareApplication node must appear on / only (found ${appNodes})`);
      }

      // Breadcrumbs. Positions must be a 1..n run, and every `item` is collected for
      // resolution against the build below — a crumb pointing at a page that does not
      // exist is the one breadcrumb failure that renders as valid markup and reads as a
      // broken trail to every consumer. There is no /docs index, so this is a live
      // hazard rather than a hypothetical.
      const trails = ofType("BreadcrumbList");
      if (trails.length > 1) {
        fail(`${routePath}: expected at most one BreadcrumbList, found ${trails.length}`);
      }
      for (const trail of trails) {
        const items = Array.isArray(trail.itemListElement) ? trail.itemListElement : [];
        if (items.length < 2) {
          fail(`${routePath}: a BreadcrumbList must carry at least two crumbs`);
        }
        items.forEach((item, index) => {
          if (item.position !== index + 1) {
            fail(`${routePath}: breadcrumb positions must run 1..n (got ${item.position})`);
          }
          if (!item.name) fail(`${routePath}: breadcrumb ${index + 1} has no name`);
          if (typeof item.item === "string") breadcrumbItemUrls.set(item.item, routePath);
          else fail(`${routePath}: breadcrumb ${index + 1} has no item URL`);
        });
      }
    } catch (error) {
      fail(`${routePath}: invalid JSON-LD (${error.message})`);
    }
  }

  // Explicit media dimensions are a repository contract (README → "Design for
  // inspection"): without them the page reflows as images decode, which is a CLS
  // regression the Lighthouse budget only catches once it is already large.
  for (const image of $("img").toArray()) {
    const width = Number($(image).attr("width"));
    const height = Number($(image).attr("height"));
    if (!Number.isFinite(width) || width <= 0 || !Number.isFinite(height) || height <= 0) {
      fail(`${routePath}: image "${$(image).attr("src")}" needs explicit dimensions`);
    }
  }
}

if (headContractPages < HEAD_CONTRACT_PAGE_FLOOR) {
  fail(
    `the head contract swept only ${headContractPages} pages (floor ` +
      `${HEAD_CONTRACT_PAGE_FLOOR}) — it is derived from the build output, so a low ` +
      `count means the build produced almost nothing, not that the site shrank`
  );
}

for (const [itemUrl, sourceRoute] of breadcrumbItemUrls) {
  await validateInternalUrl(itemUrl, sourceRoute, "breadcrumb item");
}

// Docs pages are generated from core, so their WORDS are not contracted — the head
// contract above covers their metadata. What is left here is the one thing it cannot
// infer: a BODY. Frontmatter is written from a filename and an H1, so a page whose
// document body came out empty satisfies every metadata assertion and still serves an
// HTTP 200 over nothing. A route that exists is not a document that published — see
// DOCS_BODY_TEXT_FLOOR.
for (const routePath of docsRoutePaths) {
  const filePath = path.join(distDir, routeOutputPath(routePath));
  if (!(await exists(filePath))) {
    fail(`${routePath}: missing generated docs page`);
    continue;
  }
  const $ = load(await readFile(filePath, "utf8"));
  // `.sl-markdown-content` is the rendered document only, deliberately: measuring
  // `main` would count Starlight's own sidebar, pagination and footer chrome, so a
  // page with no document at all would clear any floor on the strength of furniture.
  const body = $(".sl-markdown-content");
  if (body.length !== 1) {
    fail(
      `${routePath}: expected exactly one rendered document container, found ` +
        `${body.length} — the page is registered as a route but published no document`
    );
    continue;
  }
  const bodyText = body.text().replace(/\s+/g, " ").trim();
  if (bodyText.length < DOCS_BODY_TEXT_FLOOR) {
    fail(
      `${routePath}: docs page rendered only ${bodyText.length} characters of body ` +
        `text (floor ${DOCS_BODY_TEXT_FLOOR}) — it serves a 200 over a blank or stub ` +
        `page, which is what an allowlist entry without a working sync produces`
    );
  }
}

// Republished cross-links are the one thing about a synced corpus that can be wrong
// while looking right: `verification-and-judging.md` left un-rewritten renders as a
// normal link and 404s. So every in-site link on those pages is resolved against the
// built output — and the sweep is required to have found a real number of them, because
// a rewriter that silently matched nothing produces a page with no links to break and
// would otherwise pass this check clean.
let inSiteLinksChecked = 0;
for (const routePath of crossLinkedRoutePaths) {
  const filePath = path.join(distDir, routeOutputPath(routePath));
  if (!(await exists(filePath))) continue; // already reported by the docs loop above
  const $ = load(await readFile(filePath, "utf8"));
  // `.sl-markdown-content` is the rendered document ONLY. Sweeping `main` instead reads
  // 144 links where the corpus has 117: Starlight's prev/next pagination adds 27 in-site
  // links of its own, so the floor would then be satisfiable by chrome the sync does not
  // produce — which is the difference between measuring the corpus and measuring Starlight.
  for (const anchor of $(".sl-markdown-content a[href]").toArray()) {
    const href = $(anchor).attr("href");
    if (!href) continue;
    // An un-rewritten cross-link renders RELATIVE (`href="memory-architectures.md"`),
    // so the check is scoped to relative hrefs. Absolute `.md` URLs are Starlight's own
    // "Edit page" links, which are wrong on every docs page for an unrelated,
    // pre-existing reason (editLink.baseUrl + the generated collection path) and are
    // not this sweep's business.
    if (!/^(?:[a-z][a-z0-9+.-]*:)?\/\//i.test(href) && /\.mdx?($|[#?])/.test(href)) {
      fail(`${routePath}: un-rewritten markdown link "${href}" — it will 404`);
      continue;
    }
    if (!href.startsWith("/docs/")) continue;
    inSiteLinksChecked += 1;
    await validateInternalUrl(href, routePath, "docs cross-link", true);
  }
}
if (inSiteLinksChecked < DOCS_CROSS_LINK_FLOOR) {
  fail(
    `docs cross-link sweep checked only ${inSiteLinksChecked} in-site links ` +
      `(floor ${DOCS_CROSS_LINK_FLOOR}) — the corpus cross-references itself ` +
      `heavily, so a low count means the link rewriter degraded, not that the corpus ` +
      `changed shape`
  );
}

// The hand-authored tiers: marketing, registry index, blog and the capability matrix.
// The head contract above already checked that every page HAS metadata, that it is
// internally consistent, and that its structured data parses. What only these tiers can
// contract is the EXACT WORDS — their titles and descriptions are written in this
// repository, so a drifted string is a change to published copy and must be deliberate.
// (The /docs tier has no equivalent block on purpose: core owns those words.)
for (const route of qualityRoutes) {
  const filePath = path.join(distDir, routeOutputPath(route.path));
  if (!(await exists(filePath))) {
    fail(`${route.path}: missing generated page ${filePath}`);
    continue;
  }

  const $ = load(await readFile(filePath, "utf8"));

  if ($("title").text().trim() !== route.title) fail(`${route.path}: title does not match route contract`);
  if (metaContent($, 'meta[name="description"]') !== route.description) {
    fail(`${route.path}: description does not match route contract`);
  }
  // `website`, not Starlight's `article`: these are product pages, not documents.
  if (metaContent($, 'meta[property="og:type"]') !== "website") {
    fail(`${route.path}: og:type must be "website"`);
  }

  for (const anchor of $("a[href]").toArray()) {
    const href = $(anchor).attr("href");
    if (!href) continue;
    await validateInternalUrl(href, route.path, "link", true);
    if ($(anchor).attr("target") === "_blank") {
      const rel = new Set(($(anchor).attr("rel") ?? "").split(/\s+/));
      if (!rel.has("noreferrer") && !rel.has("noopener")) {
        fail(`${route.path}: target="_blank" link must prevent opener access: "${href}"`);
      }
    }
  }

  const resources = [
    ...$("script[src]").toArray().map((element) => $(element).attr("src")),
    ...$("img[src]").toArray().map((element) => $(element).attr("src")),
    // Media in public/ is not fingerprinted by Astro, so nothing else catches a
    // renamed or missing capture: the poster degrades to an empty box and the source
    // 404s only once a visitor presses play.
    ...$("video[src], video[poster], audio[src], source[src], track[src]")
      .toArray()
      .flatMap((element) => [$(element).attr("src"), $(element).attr("poster")]),
    ...$('link[rel="icon"], link[rel="stylesheet"], link[rel="preload"], link[rel="modulepreload"]')
      .toArray()
      .map((element) => $(element).attr("href"))
  ].filter(Boolean);
  for (const resource of resources) {
    await validateInternalUrl(resource, route.path, "resource");
  }

  const srcsetValues = [
    ...$("img[srcset]").toArray().map((element) => $(element).attr("srcset")),
    ...$("source[srcset]").toArray().map((element) => $(element).attr("srcset"))
  ].filter(Boolean);
  for (const srcset of srcsetValues) {
    for (const candidate of srcset.split(",").map((item) => item.trim().split(/\s+/)[0])) {
      await validateInternalUrl(candidate, route.path, "srcset resource");
    }
  }
}

const release$ = await readHtml("/release");
const provenance = release$("[data-release-provenance]");
if (provenance.length !== 1) {
  fail("/release: expected one release provenance root");
} else {
  const expectedAttributes = {
    "data-source-channel": releaseFacts.channel,
    "data-content-schema": String(releaseFacts.schemaVersion),
    "data-core-commit": releaseFacts.core.source.commit,
    "data-apps-commit": releaseFacts.apps.source.commit,
    "data-generated-at": releaseFacts.generatedAt
  };
  for (const [attribute, expected] of Object.entries(expectedAttributes)) {
    if (provenance.attr(attribute) !== expected) {
      fail(`/release: ${attribute} must match generated release facts`);
    }
  }
}
if (!release$.text().includes(releaseFacts.core.versionLabel)) {
  fail("/release: core version is missing from rendered provenance");
}
if (!release$.text().includes(`${releaseFacts.apps.total}`)) {
  fail("/release: app count is missing from rendered provenance");
}

for (const routePath of ["/", "/apps"]) {
  const $ = await readHtml(routePath);
  if (!$.text().includes(`${releaseFacts.apps.total}`)) {
    fail(`${routePath}: generated app count is missing`);
  }
}
const home$ = await readHtml("/");
if (!home$.text().includes(releaseFacts.core.versionLabel)) {
  fail("/: generated core version is missing");
}

const sitemapIndexPath = path.join(distDir, "sitemap-index.xml");
if (!(await exists(sitemapIndexPath))) {
  fail("missing sitemap-index.xml");
} else {
  const sitemapIndex$ = load(await readFile(sitemapIndexPath, "utf8"), { xmlMode: true });
  const sitemapUrls = sitemapIndex$("loc")
    .toArray()
    .map((element) => sitemapIndex$(element).text().trim());
  if (sitemapUrls.length === 0) fail("sitemap index contains no child sitemaps");

  const publishedUrls = new Set();
  for (const sitemapUrl of sitemapUrls) {
    const parsed = new URL(sitemapUrl);
    const sitemapPath = path.join(distDir, parsed.pathname.slice(1));
    if (!(await exists(sitemapPath))) {
      fail(`sitemap index references missing file ${parsed.pathname}`);
      continue;
    }
    const sitemap$ = load(await readFile(sitemapPath, "utf8"), { xmlMode: true });
    for (const element of sitemap$("url > loc").toArray()) {
      publishedUrls.add(sitemap$(element).text().trim().replace(/\/$/, "") || siteOrigin);
    }
  }

  // Docs pages are indexable and belong in the sitemap — that is the point of
  // publishing them for search and for LLM crawlers.
  const expectedUrls = new Set(
    [...allRoutePaths(), ...registryAppPaths].map(
      (routePath) => canonicalUrl(routePath).replace(/\/$/, "") || siteOrigin
    )
  );
  if (
    publishedUrls.size !== expectedUrls.size ||
    [...expectedUrls].some((url) => !publishedUrls.has(url))
  ) {
    fail(`sitemap routes differ: expected ${[...expectedUrls].join(", ")}, got ${[...publishedUrls].join(", ")}`);
  }
}

const robotsPath = path.join(distDir, "robots.txt");
if (!(await exists(robotsPath))) {
  fail("missing robots.txt");
} else {
  const robots = await readFile(robotsPath, "utf8");
  if (expectNoIndex) {
    if (!/^Disallow: \/$/m.test(robots)) fail("preview robots.txt must disallow all crawling");
  } else {
    if (!/^Allow: \/$/m.test(robots)) fail("production robots.txt must allow crawling");
    if (!robots.includes(`Sitemap: ${siteOrigin}/sitemap-index.xml`)) {
      fail("production robots.txt must name the canonical sitemap");
    }
    // robots.txt is the first file an agent fetches, and it is the only place this site
    // can point one at the machine-readable corpus — there is no directive for it, so
    // the pointer is a comment. Contracted so the pointer and the files cannot drift
    // apart: the pair below is asserted to exist in the same run.
    for (const llmsPath of [llmsIndexPath, llmsFullPath]) {
      if (!robots.includes(`${siteOrigin}${llmsPath}`)) {
        fail(`production robots.txt must point at ${siteOrigin}${llmsPath}`);
      }
    }
  }
}

// ── The machine-readable corpus (llmstxt.org) ────────────────────────────────────
//
// Generated by scripts/sync-docs.mjs from the same pinned commit as /docs and gitignored,
// so nothing in the repository proves they were written. `public/` is copied verbatim: a
// writer that threw, a renamed output, or a broadened ignore rule each produce a site
// that looks complete and has quietly stopped being legible to an agent — the same shape
// as a docs route that 200s over a blank page.
{
  const versionLabel = releaseFacts.core.versionLabel;
  for (const [llmsPath, floor] of [
    [llmsIndexPath, LLMS_INDEX_BYTE_FLOOR],
    [llmsFullPath, LLMS_FULL_BYTE_FLOOR]
  ]) {
    const filePath = path.join(distDir, llmsPath.slice(1));
    if (!(await exists(filePath))) {
      fail(`missing ${llmsPath} — run \`npm run sync:docs\``);
      continue;
    }
    const body = await readFile(filePath, "utf8");
    if (body.length < floor) {
      fail(
        `${llmsPath} is ${body.length} bytes (floor ${floor}) — a header-only or ` +
          `truncated write, not a corpus`
      );
    }
    // The corpus must name the release it was generated from, for the same reason every
    // other surface here does: an undated document about a moving product is a guess.
    if (!body.includes(versionLabel)) {
      fail(`${llmsPath} does not name the pinned release ${versionLabel}`);
    }
  }

  const indexPath = path.join(distDir, llmsIndexPath.slice(1));
  if (await exists(indexPath)) {
    const index = await readFile(indexPath, "utf8");
    const linked = new Set(
      [...index.matchAll(new RegExp(`${siteOrigin}(/[\\w\\-/.]*)`, "g"))].map(
        (match) => match[1].replace(/[.,)]$/, "")
      )
    );
    // Every URL it advertises must resolve. An index of 404s is worse than no index:
    // the agent that reads it has no other way to discover it was wrong.
    for (const linkedPath of linked) {
      await validateInternalUrl(`${siteOrigin}${linkedPath}`, llmsIndexPath, "llms.txt link");
    }
    // …and it must advertise the WHOLE corpus. Set equality both ways, so a doc published
    // without an llms.txt entry fails as loudly as an entry for a doc that was withdrawn.
    // This is what makes the human-facing and agent-facing views of /docs one surface.
    const linkedDocs = new Set([...linked].filter((entry) => entry.startsWith("/docs")));
    for (const docsRoute of docsRoutePaths) {
      if (!linkedDocs.has(docsRoute)) fail(`${llmsIndexPath} does not list ${docsRoute}`);
    }
    for (const linkedDoc of linkedDocs) {
      if (!docsRoutePaths.includes(linkedDoc)) {
        fail(`${llmsIndexPath} lists ${linkedDoc}, which is not a published docs route`);
      }
    }
  }
}

const trackerPatterns = [
  /google-analytics\.com/i,
  /googletagmanager\.com/i,
  /plausible\.io/i,
  /cdn\.segment\.com/i,
  /api\.segment\.io/i,
  /posthog/i,
  /mixpanel/i,
  /hotjar/i,
  /clarity\.ms/i,
  /connect\.facebook\.net/i
];

async function scanTextFiles(directory) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      await scanTextFiles(entryPath);
      continue;
    }
    if (!/\.(?:css|html|js|json|txt|xml)$/.test(entry.name)) continue;
    const content = await readFile(entryPath, "utf8");
    for (const pattern of trackerPatterns) {
      if (pattern.test(content)) {
        fail(`tracker signature ${pattern} found in ${path.relative(root, entryPath)}`);
      }
    }
  }
}

await scanTextFiles(distDir);

const vercel = JSON.parse(await readFile(path.join(root, "vercel.json"), "utf8"));
if (vercel.framework !== "astro") fail('vercel.json framework must be "astro"');
if (vercel.buildCommand !== "npm run build") fail('vercel.json must use "npm run build"');
if (vercel.outputDirectory !== "dist") fail('vercel.json outputDirectory must be "dist"');
// ONE URL per page. Astro is configured `trailingSlash: "never"` and writes the
// slash-free form into every canonical, og:url and sitemap entry — but Astro only
// decides what it EMITS. With this key absent, Vercel serves `/product/index.html` at
// both `/product` and `/product/` with a 200 and no redirect, which was measured on
// production: two URLs for one page, held together by nothing but rel=canonical. `false`
// makes Vercel 308 the slashed form onto the canonical one, so the two halves agree.
if (vercel.trailingSlash !== false) {
  fail(
    'vercel.json must set "trailingSlash": false to agree with astro.config.mjs ' +
      "(trailingSlash: \"never\"); without it both /x and /x/ answer 200"
  );
}
const securityHeaders = new Set(
  (vercel.headers ?? []).flatMap((rule) => (rule.headers ?? []).map((header) => header.key))
);
for (const header of [
  "Cross-Origin-Opener-Policy",
  "Permissions-Policy",
  "Referrer-Policy",
  "X-Content-Type-Options",
  "X-Frame-Options"
]) {
  if (!securityHeaders.has(header)) fail(`vercel.json is missing ${header}`);
}
// The install script is served as text/plain, so it cannot carry a robots meta tag and
// nothing else can keep it out of a result list. A header is the only mechanism available,
// and an installer ranking for the product's name is noise at best.
{
  const installRule = (vercel.headers ?? []).find((rule) => rule.source === "/install");
  const installHeaders = new Map(
    (installRule?.headers ?? []).map((header) => [header.key, header.value])
  );
  if (installHeaders.get("X-Robots-Tag") !== "noindex") {
    fail('vercel.json must serve /install with "X-Robots-Tag: noindex"');
  }
}

// ── CTA canon + nav parity (PRODUCT.md: the primary CTA is "Get PersonalClaw") ──
//
// Three labels once pointed the SAME primary-button treatment at the SAME
// destination ("Get PersonalClaw" / "Read the repository" / "View the source").
// The rule from PRODUCT.md is checked against the RENDERED output: every
// `button-primary` anchor whose destination is the core GitHub repository must
// carry the canonical label. Anchors to other destinations (a tour, a guide,
// an in-page jump) keep their own verbs — the canon binds the conversion CTA,
// not every loud button.
const CTA_CANON = "Get PersonalClaw";
const CORE_REPO_URL = "https://github.com/PersonalClaw/PersonalClaw";
for (const route of routes) {
  const filePath = localOutputPath(route.path);
  if (!(await exists(filePath))) {
    fail(`${route.path}: no built output at ${path.relative(root, filePath)} for the CTA sweep`);
    continue;
  }
  const $ = load(await readFile(filePath, "utf8"));
  $("a.button-primary").each((_, el) => {
    const href = ($(el).attr("href") ?? "").replace(/\/+$/, "");
    if (href !== CORE_REPO_URL) return;
    const label = $(el).text().replace(/\s+/g, " ").trim();
    if (!label.startsWith(CTA_CANON)) {
      fail(
        `${route.path}: primary CTA to the core repository must carry the canonical ` +
          `label "${CTA_CANON}" (found "${label}")`
      );
    }
  });
}

// The header names the site's primary internal routes; the footer is the
// long-tail nav and must not silently drop any of them — a route reachable
// from the sticky header but absent from the footer reads as deprecated.
{
  const home$ = load(await readFile(localOutputPath("/"), "utf8"));
  const headerInternal = new Set(
    home$("header nav a[href^='/']")
      .map((_, el) => home$(el).attr("href"))
      .get()
  );
  const footerHrefs = new Set(
    home$("footer a[href^='/']")
      .map((_, el) => home$(el).attr("href"))
      .get()
  );
  for (const href of headerInternal) {
    if (href === "/") continue;
    if (!footerHrefs.has(href)) {
      fail(`footer navigation is missing header route ${href}`);
    }
  }
  // The header's conversion CTA carries the canon too (it is the one CTA
  // rendered on every page, so drift here multiplies across the whole site).
  const headerCta = home$("header a.button-primary").first();
  const headerLabel = headerCta.text().replace(/\s+/g, " ").trim();
  if (!headerCta.length) {
    fail("the sticky header must render the primary conversion CTA");
  } else if (!headerLabel.startsWith(CTA_CANON)) {
    fail(`the header CTA must carry "${CTA_CANON}" (found "${headerLabel}")`);
  }
}

// ── The hand-authored catalog must equal the pinned release's manifests (AUD-X1b) ──
// src/data/apps.ts is authored by hand; .generated/release-facts.json is derived from the
// pinned apps-repo commit. The two matched by authorship when this check landed (39 == 39),
// which is exactly the kind of parity that drifts silently: an app added to the next release
// pin, or renamed, would leave the catalog lying about the release it claims to project.
// Set equality, both directions, so the failure names the drifted slug.
{
  const appsTs = await readFile(path.join(root, "src", "data", "apps.ts"), "utf8");
  const catalogSlugs = new Set(
    [...appsTs.matchAll(/slug:\s*"([^"]+)"/g)].map((m) => m[1])
  );
  const pinnedNames = new Set(releaseFacts.apps.manifests.map((m) => m.name));
  for (const name of pinnedNames) {
    if (!catalogSlugs.has(name)) {
      fail(`apps.ts is missing "${name}", which ships at the pinned apps commit`);
    }
  }
  for (const slug of catalogSlugs) {
    if (!pinnedNames.has(slug)) {
      fail(`apps.ts lists "${slug}", which does not exist at the pinned apps commit`);
    }
  }
}

if (failures.length > 0) {
  console.error(failures.map((failure) => `- ${failure}`).join("\n"));
  process.exitCode = 1;
} else {
  console.log(
    `Validated ${routes.length} marketing routes + ${docsRoutePaths.length} docs pages + ` +
      `the registry index and ${registryAppPaths.length} per-listing page(s) ` +
      `(registry ${registryListing().state}) + ${blogRoutes.length} blog page(s) + ` +
      `${compareRoutes.length} compare page(s) in ` +
      `${path.relative(root, distDir)} (${expectNoIndex ? "preview" : "production"} policy); ` +
      `resolved ${inSiteLinksChecked} in-site docs links across ` +
      `${crossLinkedRoutePaths.length} link-swept docs pages.`
  );
  // Printed so a green can be read against a real denominator: the head contract is
  // derived from the build output, so its coverage is a measurement rather than a list.
  console.log(
    `Head contract: ${headContractPages} page(s) swept (floor ` +
      `${HEAD_CONTRACT_PAGE_FLOOR}); ${breadcrumbItemUrls.size} distinct breadcrumb ` +
      `target(s) resolved; social card ${socialImageWidth}x${socialImageHeight} verified ` +
      `against ${socialImagePath}; ${llmsIndexPath} + ${llmsFullPath} published and ` +
      `cross-checked against ${docsRoutePaths.length} docs route(s).`
  );
}
