import { defineCollection } from "astro:content";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

// Starlight needs the `docs` collection declared before it will render
// src/content/docs/. That directory is GENERATED by scripts/sync-docs.mjs from the
// pinned core commit and is gitignored — see the note in astro.config.mjs.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() })
};
