import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";
import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";

// Starlight needs the `docs` collection declared before it will render
// src/content/docs/. That directory is GENERATED by scripts/sync-docs.mjs from the
// pinned core commit and is gitignored — see the note in astro.config.mjs.
const docs = defineCollection({ loader: docsLoader(), schema: docsSchema() });

// The BLOG collection is the inverse of `docs` in the one way that matters: its files
// are SOURCE-CONTROLLED here, because these are this site's own words rather than
// core's. Never move a post under src/content/docs/ — that tree is regenerated from the
// pinned core commit on every build and a post placed there would simply vanish.
//
// `verifiedAgainst` is required on purpose. A post makes product claims, and this site
// publishes RELEASED state (README → "Content And Release Truth"), so every post has to
// say which release its claims were checked against. A post that cannot name one has no
// business being published here.
const blog = defineCollection({
  loader: glob({ base: "./src/content/blog", pattern: "**/*.md" }),
  schema: z.object({
    title: z.string().min(1),
    description: z.string().min(1),
    publishDate: z.date(),
    verifiedAgainst: z.string().min(1)
  })
});

export const collections = { docs, blog };
